version: '3.7'

services:
  postgres-db:
    image: postgres:16.1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: amplifyi
      POSTGRES_DB: amplifyi
      POSTGRES_PASSWORD: changeme
    networks:
      - ai-net
    ports:
      - "5432:5432"

networks:
  ai-net:
    external: false
